name: flutter_jd
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # 轮播图
  flutter_swiper: ^1.1.6
  # 设备信息
  device_info: ^0.4.2+4
  # 网络请求
  dio: ^4.0.0
  # 提示
  bot_toast: ^3.0.0
  shared_preferences: ^0.5.7+3
  connectivity: ^0.4.2
  # 下拉刷新
  pull_to_refresh: ^2.0.0
  # 侧滑菜单
  flutter_slidable: ^0.6.0
  # getx
  get: ^4.1.4
  # 系统文字中英文
  flutter_cupertino_localizations: ^1.0.1
  # 授权
  permission_handler: ^8.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: Iconfont
      fonts:
        - asset: assets/iconfont/iconfont.ttf

  assets:
    - assets/images/launch/ad.jpg
    - assets/images/my/my_bg.png
    - assets/images/home/ms.png
    - assets/images/common/avatar.png

    - assets/images/common/refresh.gif

    - assets/images/banner/banner_jd_1.jpg
    - assets/images/banner/banner_jd_2.jpg
    - assets/images/banner/banner_jd_3.jpg
    - assets/images/banner/banner_jd_4.jpg
    - assets/images/banner/banner_jd_5.jpg
    - assets/images/banner/banner_jd_6.jpg
    - assets/images/banner/banner_jd_7.jpg
    - assets/images/banner/banner_jd_8.jpg

    - assets/images/icon/icon_a_1.png
    - assets/images/icon/icon_a_2.png
    - assets/images/icon/icon_a_3.png
    - assets/images/icon/icon_a_4.png
    - assets/images/icon/icon_a_5.png
    - assets/images/icon/icon_a_6.png
    - assets/images/icon/icon_a_7.png
    - assets/images/icon/icon_a_8.png
    - assets/images/icon/icon_a_9.png
    - assets/images/icon/icon_a_10.png

    - assets/images/icon/icon_b_1.png
    - assets/images/icon/icon_b_2.png
    - assets/images/icon/icon_b_3.png
    - assets/images/icon/icon_b_4.png
    - assets/images/icon/icon_b_5.png
    - assets/images/icon/icon_b_6.png
    - assets/images/icon/icon_b_7.png
    - assets/images/icon/icon_b_8.png
    - assets/images/icon/icon_b_9.png
    - assets/images/icon/icon_b_10.png

    - assets/images/product/product_1.jpg
    - assets/images/product/product_2.jpg
    - assets/images/product/product_3.jpg
    - assets/images/product/product_4.jpg
    - assets/images/product/product_5.jpg
    - assets/images/product/product_6.jpg
    - assets/images/product/product_7.jpg
    - assets/images/product/product_8.jpg

    - assets/images/tools/tool_1.png
    - assets/images/tools/tool_2.png
    - assets/images/tools/tool_3.png
    - assets/images/tools/tool_4.png
    - assets/images/tools/tool_5.png
    - assets/images/tools/tool_6.png
    - assets/images/tools/tool_7.png
    - assets/images/tools/tool_8.png
    - assets/images/tools/tool_9.png
    - assets/images/tools/tool_10.png
